pipeline{

    agent{label('any')}

    environment {
        //AWS_ACCOUNT_ID='aws account number'
        //AWS_DEFAULT_REGION='region'
        //IMAGE_REPO-NAME='jenkins/spring-pet'
        //IMAGE_TAG='1.0'
        //REPOSITORY_URI='${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO-NAME}'
        registry='pvenkateswararo/app.js'
        dockerImage=''
        registryCredential='Dockerhub_id'
    }

    stages{
        stage('scm'){
            steps{
                git ''
            }
        }
        stage('docker image build'){
            steps{
                sh 'sudo docker image build -t ${registry}:1.2'
            }
        }
        stage('push to dockerhub'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'Dockerhub_id', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]){
                    sh "sduo docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                    sh 'sudo docker push ${registry}:1.2'
                }
            }
        }
        stage('deploy in k8s'){
            steps{
                sh 'kubectl apply -f app-js-deployment.yml'
            }
        }
    }
}