---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  provisioner: kubernetes.io/aws-ebs
  parameters:
    type: gp2
    fsType: ext4
    zone: us-west-2a, us-west-2b, us-west-2c
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: web
spec:
  storageClassName: mysql-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Mysql
  labels:
    app: web
spec:
  containers:
    - name: mysql-container
      image: 419784164229.dkr.ecr.us-west-2.amazonaws.com/mysql:latest
      volumeMounts:
            - mountPath: "/var/lib/mysql"
              persistentVolumeClaim:
              claimName: mysql-pvc
      env:
          - name: MYSQL_DATABASE
            value: 'testing'
          - name: MYSQL_USER
            value: 'myfrstsql'
          - name: MYSQL_PASSWORD
            value: '1234'
          - name: MYSQL_ROOT_PASSWORD
            value: 'password'        
      ports:
        - containerPort: 3306  