---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: web
spec:
  storageClassName: mysql-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    