---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-mrs
  labels:
    app: openmrs
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: openmrs
  containers:
    - name: open-mrs-container
      image:
      ports:
        - containerPorts: 8080
