---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-mrs
  labels:
    app: openmrs
spec:
  selector:
    matchLabels:
      app: openmrs
  replicas: 3    
  template:
    metadata:
      labels:
        app: openmrs  
   spec:      
     containers:
       - name: open-mrs-container
         image: pvenkateswarrao/open-mrs:1.0
         ports:
           - containerPorts: 8080
      imagePullSecrets:
        - name: dockersecerts

